"""change the User's picture column

Revision ID: 0222fb38e0bd
Revises: a8b790294542
Create Date: 2017-01-13 02:56:33.176443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0222fb38e0bd'
down_revision = 'a8b790294542'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
