"""change the Integer to INT

Revision ID: 077fd923c549
Revises: 4505dce67adb
Create Date: 2017-01-09 09:21:15.965124

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '077fd923c549'
down_revision = '4505dce67adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materials', 'amount')
    op.drop_column('materials', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('test', mysql.TINYTEXT(), nullable=True))
    op.add_column('materials', sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
