"""change the steps technique 50 - 150

Revision ID: 12648e5aa177
Revises: b72297d14fec
Create Date: 2017-01-18 06:09:42.071024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12648e5aa177'
down_revision = 'b72297d14fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'technique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('technique', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
