"""update step on clumn string(50) as sting(100)

Revision ID: 1df5c15ee948
Revises: 5d87a5b7f933
Create Date: 2017-01-10 00:54:10.978401

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1df5c15ee948'
down_revision = '5d87a5b7f933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('pictures', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'pictures')
    # ### end Alembic commands ###
