"""add recipe author column

Revision ID: 233889b9c607
Revises: dcfe1af606ff
Create Date: 2017-01-11 09:45:41.377230

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '233889b9c607'
down_revision = 'dcfe1af606ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author', sa.Text(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'author')
    # ### end Alembic commands ###
