"""change the steps technique 50 - 150

Revision ID: 3319bf358b5a
Revises: 12648e5aa177
Create Date: 2017-01-18 06:10:19.306136

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '3319bf358b5a'
down_revision = '12648e5aa177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('technique', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'technique')
    # ### end Alembic commands ###
