"""add user's picture column

Revision ID: 792977edaf72
Revises: cfd53030abff
Create Date: 2017-01-13 03:46:22.598713

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '792977edaf72'
down_revision = 'cfd53030abff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('picture', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
