"""init

Revision ID: 9c72232f8f14
Revises: 
Create Date: 2017-01-09 07:38:58.931561

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9c72232f8f14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(length=20), nullable=True),
                    sa.Column('introduce', sa.Text(length=100), nullable=True),
                    sa.Column('pictures', sa.String(length=50), nullable=True),
                    sa.Column('tips', sa.Text(length=100), nullable=True),
                    sa.Column('author', sa.Text(length=20), nullable=True),
                    sa.Column('create_time', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.Column('password', sa.Text(length=100), nullable=True),
                    sa.Column('email', sa.String(length=30), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('create_time', sa.String(length=30), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('materials',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('material_number', sa.Integer(), nullable=True),
                    sa.Column('name', sa.Text(length=20), nullable=True),
                    sa.Column('amount', sa.Integer(), nullable=True),
                    sa.Column('recipe_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('steps',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('step_number', sa.Integer(), nullable=True),
                    sa.Column('technique', sa.String(length=50), nullable=True),
                    sa.Column('pictures', sa.String(length=50), nullable=True),
                    sa.Column('recipe_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('steps')
    op.drop_table('materials')
    op.drop_table('user')
    op.drop_table('recipes')
    # ### end Alembic commands ###
