"""delete author column in recipe table

Revision ID: a8b790294542
Revises: 05ad71511e69
Create Date: 2017-01-12 02:41:13.185450

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a8b790294542'
down_revision = '05ad71511e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('author', sa.Text(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'author')
    # ### end Alembic commands ###
