"""add Debug table

Revision ID: c9d1ec0bce60
Revises: 3319bf358b5a
Create Date: 2017-01-20 08:41:50.913184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d1ec0bce60'
down_revision = '3319bf358b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('debug',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('debug_content', sa.Text(length=150), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('create_time', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debug')
    # ### end Alembic commands ###
