"""add foreign_key for questions

Revision ID: f672fa517a27
Revises: 90b085e26ad5
Create Date: 2017-01-11 06:38:13.574170

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f672fa517a27'
down_revision = '90b085e26ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'questions', 'recipes', ['recipe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # ### end Alembic commands ###
